### ISSUE TITLE
Add support for eslint 8.x and @typescript-eslint/parser 5.x

### ISSUE THREAD

**Issue by kamui** [hpersson/eslint-plugin-jsx-expressions#1]
Thanks for this plugin. Recently, we've wanted to upgrade eslint to 8.x and typescript-eslint to 5.x, but this was the only plugin we use that has a peer dependency for the older major version. So just requesting support for eslint 8.x and @typescript-eslint/parser 5.x. Thanks!

**Comment by hpersson** [comment]
Fixed in version 1.3
