### ISSUE TITLE
TypeScript required?

### ISSUE THREAD

**Issue by frankcalise** [hpersson/eslint-plugin-jsx-expressions#8]
Hello - I'm trying to use your plugin in my Expo project but am receiving the following error after setup:

`Failed to load plugin 'jsx-expressions' declared in '.eslintrc.js': Cannot find module 'typescript' Require stack: -`

I don't have typescript used at all in this project, is this necessary for me to use this plugin? Any suggestions?

**Comment by branislaav** [comment]
Hi, `eslint-plugin-jsx-expressions` package only works with `@typescript-eslint/parser`, and uses type information. So I don't think it will work without typescript.

**Comment by hpersson** [comment]
Yup, @branislaav is correct - TypeScript is required to use the plugin!
